# Generated by Django 5.1.1 on 2024-09-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FORNECEDOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_f', models.CharField(max_length=80)),
                ('cnpj', models.IntegerField(max_length=18, unique=True)),
                ('produto', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
